Description: >
  This is a template that creates EC2 instances, VPC, Subnet, RoutingTable and

Parameters:
  SshKeyPair:
    Type: String
    Default: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDAlVjPoTZEQU/2jhXi94qIF1XvGKie46HFIexZlrXdgdYnRuRMeQKiN1LJ0S/CBMhzX/9CH8PnSasQ35AFBdhnECrKHc5jA6p7Xw0ivBKCBw5faVIoN+sYHQxbxpB305FH7VLVp6LEx8JdlnO5aVXQf7sqK9ZppbcZyH7TtiKYw8SYDR3PWugJ5poFnEP8Aub0Zzgz6+9IVnSB+575geZAwiozEEka/4QXCLBp6n5OGDFE78QHOWE3w1kxfdPmntKOKOttdr1L2gPAliWKsJ2afamGqga8afbi2yMnop7ygtrER19wc1xlNTVPZ1I70Jf3ECYTCAbxlSdGrDuP274l1iirMXo22B/JjQTQRVvrE8m0j/DQQ83ZGW3pRvTA96MTpDx2wlHS0H28nMgVVcKSHNZMkV++Mdt53G3E40FwvoQskKqv5MNOiIZFH2RZ9XsDRLi8oVR5KIspOTPgM4aJgeWrmNhOjQV+yJf1/W8g4xfYkuymYVFB7ZqtJjIhblE= nim@Nima.local

Mappings:
    RegionToAmazonAMI:
        us-east-1:
            UB20: ami-0070c5311b7677678
        ap-southeast-2:
            UB20: ami-048a2d001938101dd

Resources:
  MySshKey:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: NimaMacbookPro
      PublicKeyMaterial: !Ref SshKeyPair
  MyInternetGateway:
    Type: AWS::EC2::InternetGateway
  FirstVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
  MyGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref MyInternetGateway
      VpcId: !Ref FirstVPC
  MyRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref FirstVPC
  MyRoute:
    DependsOn:
      - MyInternetGateway
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId: !Ref MyInternetGateway
      RouteTableId: !Ref MyRouteTable
  MyFirstSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref FirstVPC
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: "us-east-1a"
      MapPublicIpOnLaunch: "true"
  MyRouteTableAssosiation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref MyFirstSubnet
      RouteTableId: !Ref MyRouteTable
  EC2SecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: 'Permitting SSH From Pritunl Sydney'
        VpcId: !Ref FirstVPC
        SecurityGroupIngress:
            - IpProtocol: tcp
              FromPort: 22
              ToPort: 22
              CidrIp: 158.176.95.134/32
  BastionEc2Instance: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId:
        Fn::FindInMap:
            - RegionToAmazonAMI
            - Ref: 'AWS::Region'
            - UB20
      InstanceType: t2.medium
      KeyName: !Ref MySshKey
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet:
            - !Ref EC2SecurityGroup
          SubnetId: !Ref MyFirstSubnet
      Tags:
        - Key: Name
          Value: Bastion
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          cd /home/ubuntu/
          sudo apt update && sudo apt install -y curl unzip
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --bin-dir /usr/local/bin
          echo "complete -C '/usr/local/bin/aws_completer' aws" >> /home/ubuntu/.bashrc
          echo ${SshKeyPair} >> /home/ubuntu/pubIp.txt

Outputs:
  BastionPublicIP:
    Value: !GetAtt BastionEc2Instance.PublicIp
    Description: "Bastion's Public ip"

