---
- hosts: k8sControlPlane-Jenkins
  become: yes
  remote_user: ubuntu
  become_user: root
  tasks:

  - name: Installing Java 11 on Jenkins instance
    ansible.builtin.apt:
      name: openjdk-11-jdk
      state: present
      update_cache: yes
  - name: Installing fontconfig on Jenkins instance
    ansible.builtin.apt:
      name: fontconfig
      state: present
  - name: Adding Jenkins apt key
    ansible.builtin.apt_key:
      url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
      state: present
  - name: Add Jenkins repository into sources list
    ansible.builtin.apt_repository:
      repo: deb https://pkg.jenkins.io/debian-stable binary/
      state: present
  - name: Installing Jenkins Service on Jenkins instance
    ansible.builtin.apt:
      name: jenkins
      state: present
  - name: Start service Jenkins, if not started
    ansible.builtin.service:
      name: jenkins
      state: started
  - name: Removing /var/lib/jenkins
    ansible.builtin.file:
      path: /var/lib/jenkins
      state: absent
  - name: Clone Jenkins home dir
    ansible.builtin.git:
      repo: https://github.com/mrnimic/jenkins.git
      dest: /var/lib/jenkins
      clone: yes
      update: yes
  - name: Recursively change ownership of Jenkins Home dir
    ansible.builtin.file:
      path: /var/lib/jenkins
      state: directory
      recurse: yes
      owner: jenkins
      group: jenkins
  - name: Restart Jenkins service, in all cases
    ansible.builtin.service:
      name: jenkins
      state: restarted
  - name: Setting k8s-control hostname
    ansible.builtin.hostname:
      name: k8s-control
  - name: Editing /etc/hosts for Jenkins host
    ansible.builtin.lineinfile:
      path: /etc/hosts
      line: "{{ jenkins_private_ip }} k8s-control"
  - name: Editing /etc/hosts for Worker1 host
    ansible.builtin.lineinfile:
      path: /etc/hosts
      line: "{{ worker1_private_ip }} k8s-worker1"
  - name: Editing /etc/hosts for Worker2 host
    ansible.builtin.lineinfile:
      path: /etc/hosts
      line: "{{ worker2_private_ip }} k8s-worker2"
  - name: Editing /etc/modules-load.d/containerd.conf
    ansible.builtin.lineinfile:
      path: /etc/modules-load.d/containerd.conf
      line: "overlay"
  - name: Editing /etc/modules-load.d/containerd.conf
    ansible.builtin.lineinfile:
      path: /etc/modules-load.d/containerd.conf
      line: "br_netfilter"
  - name: Add the overlay module
    modprobe:
      name: overlay
      state: present
  - name: Add the br_netfilter module
    modprobe:
      name: br_netfilter
      state: present
  - name: Ensure net.bridge.bridge-nf-call-iptables is set to 1
    ansible.builtin.lineinfile:
      path: /etc/selinux/config
      regexp: '^net.bridge.bridge-nf-call-iptables.*'
      line: net.bridge.bridge-nf-call-iptables = 1
  # In order to test vars
  - name: writing in file
    ansible.builtin.copy:
      content: "{{ worker1_private_ip }}"
      dest: /home/ubuntu/workerip.txt