- name: Set Master hostname.
  become: yes
  become_user: root
  hostname:
    name: control-plane

- name: Add Google official GPG key
  become: yes
  become_user: root
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add Kubernetes Repository
  become: yes
  become_user: root
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main 
    state: present
    filename: kubernetes
    mode: 0600
    
- name: Install prerequisite packages.
  become: yes
  become_user: root
  ansible.builtin.apt:
    name:
      - python3
      - unzip
      - kubectl
    state: present
    update_cache: yes

######## AWSCLI

- name: Download the awscli bundle.
  get_url: url=https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip dest=/tmp/awscliv2.zip
  register: aws_cli_download_bundle

- name: Unarchive the installer.
  unarchive: src=/tmp/awscliv2.zip dest=/tmp copy=no creates=/tmp/awscli
  when: aws_cli_download_bundle.changed
  register: aws_cli_unarchive_installer

- name: Install awscli package.
  become: yes
  become_user: root
  shell: /tmp/aws/install -i /usr/local/aws -b /usr/bin/
  when: aws_cli_unarchive_installer.changed

- name: Create .aws Directory
  file:
    path: /home/ubuntu/.aws
    state: directory

- name: Configure AWS.
  shell: echo "{{ hostvars['AWS_TOKEN_HOLDER']['token'] }}" > /home/ubuntu/.aws/credentials

- name: aws-cli autocomplete
  ansible.builtin.lineinfile:
    path: /home/ubuntu/.bashrc
    line: complete -C '/usr/bin/aws_completer' aws


######## Update kubeconfig
- name: Update kubeconfig
  shell: aws eks update-kubeconfig --region us-east-1 --name {{ cluster_name }}


- name: add alias k for kubectl
  ansible.builtin.lineinfile:
    path: /home/ubuntu/.bashrc
    line: alias k='kubectl'

- name: kubectl autocomplete script
  shell: kubectl completion bash | sudo tee /etc/bash_completion.d/kubectl

- name: autocompletion for k
  ansible.builtin.lineinfile:
    path: /home/ubuntu/.bashrc
    line: complete -o default -F __start_kubectl k

######## HELM

- name: Download Helm
  get_url: url=https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 dest=/home/ubuntu/get_helm.sh
  register: helm_download

- name: Make the script executable
  when: helm_download.changed
  file:
    path: /home/ubuntu/get_helm.sh
    mode: '0700'

- name: Install Helm
  shell: /home/ubuntu/get_helm.sh
  when: helm_download.changed

- name: add alias h for helm
  ansible.builtin.lineinfile:
    path: /home/ubuntu/.bashrc
    line: alias h='helm'

- name: helm autocomplete script
  shell: helm completion bash | sudo tee /etc/bash_completion.d/helm

- name: autocompletion for h
  ansible.builtin.lineinfile:
    path: /home/ubuntu/.bashrc
    line: complete -o default -F __start_helm h

######## Clone kiamol repo

- name: create kiamol directory
  ansible.builtin.file:
    path: /home/ubuntu/kiamol
    state: directory

- name: clone kiamol
  ansible.builtin.git:
    repo: 'https://github.com/sixeyed/kiamol.git'
    dest: /home/ubuntu/kiamol
    version: master
